
const nav=document.querySelector('.nav'),menu=document.querySelector('.menu');menu?.addEventListener('click',()=>{const o=nav.classList.toggle('open');menu.setAttribute('aria-expanded',o)});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const reveals=document.querySelectorAll('.reveal');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});reveals.forEach(x=>io.observe(x));
document.querySelectorAll('.work-item button').forEach(b=>b.addEventListener('click',()=>b.closest('.work-item').classList.toggle('open')));
const counterIO=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=+el.dataset.count,prefix=el.dataset.prefix||'',start=performance.now(),dur=1300;function tick(now){const p=Math.min((now-start)/dur,1),v=Math.round(target*(1-Math.pow(1-p,3)));el.textContent=prefix+v.toLocaleString();if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);counterIO.unobserve(el)}),{threshold:.5});document.querySelectorAll('[data-count]').forEach(x=>counterIO.observe(x));
const swap=document.querySelector('.word-swap');if(swap){const ws=swap.dataset.words.split(',');let i=0;setInterval(()=>{swap.animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(-10px)'},{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],{duration:500});i=(i+1)%ws.length;setTimeout(()=>swap.textContent=ws[i],245)},2600)}
document.querySelectorAll('.filters button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;document.querySelectorAll('.media-card').forEach(c=>c.classList.toggle('hidden',f!=='all'&&c.dataset.category!==f))}));
const lb=document.querySelector('.lightbox'),lbimg=lb.querySelector('img');document.querySelectorAll('.gallery-item').forEach(g=>g.addEventListener('click',()=>{lbimg.src=g.dataset.full;lb.classList.add('open');lb.setAttribute('aria-hidden','false')}));function close(){lb.classList.remove('open');lb.setAttribute('aria-hidden','true')}lb.querySelector('button').addEventListener('click',close);lb.addEventListener('click',e=>{if(e.target===lb)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});document.querySelectorAll('[data-year]').forEach(e=>e.textContent=new Date().getFullYear());
